name: Deploy to NetAngels

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Забрать код
        uses: actions/checkout@v4

      - name: Установить Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Установить зависимости
        run: npm ci

      - name: Собрать проект
        run: npm run build

      - name: Исправить роутинг (SPA)
        run: |
          echo "RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]" > build/.htaccess

      - name: Залить на NetAngels
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          server-dir: /www/algoritm23.net/
          dangerous-clean-slate: true